import { Pressable, StyleSheet, Text } from 'react-native';
import { useRouter } from 'expo-router';
import { BrandHeader } from '@/components/BrandHeader';
import { Screen } from '@/components/Screen';
import { colors, spacing, type } from '@/constants/theme';

export default function TermsScreen() {
  const router = useRouter();
  return <Screen header={<BrandHeader compact title="Terms and Community Rules" />}><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹ Back</Text></Pressable><Text style={styles.title}>Trust requires honest participation</Text><Rule title="Completed experiences only">Share a service experience only after real work occurred. Use the actual reported cost and month/year. Do not post a private address, exact service date, confidential document, or unrelated personal information.</Rule><Rule title="Independent labels">Community-shared, provider self-listed, Sponsored, verified, claimed, and unknown states are labeled separately. Sponsored placement never changes a rating, Trust Star, referral badge, or review visibility.</Rule><Rule title="Fair reviews and replies">A provider may respond or report but cannot edit another person’s genuine experience. Users must not fabricate jobs, coordinate rating manipulation, harass others, or farm referral badges.</Rule><Rule title="Rewards">A voluntary thank-you may recognize a verified referral contribution. It may never require positive sentiment, a minimum rating, review removal, or concealment of material benefit.</Rule><Rule title="Regulated work">Users must check licensing, insurance, permits, and suitability with the appropriate local authority. HouseFriends does not claim credential verification unless it is explicitly labeled as verified.</Rule><Rule title="Moderation and appeals">HouseFriends may filter, limit, remove, or preserve content and accounts to protect privacy, safety, integrity, and legal compliance. Reports are risk-prioritized, actions are audited, and affected users may appeal.</Rule><Rule title="Provider authority">Signing in with Google or Apple proves control of an account, not authority over a company. Company and branch claims require separate verification. Human admins remain public aliases.</Rule><Rule title="Final legal terms">Before public launch, counsel must add the operating entity, governing law, dispute terms, warranty and liability provisions, payment terms for any activated promotion, and jurisdiction-specific notices.</Rule></Screen>;
}
function Rule({ title, children }: { title: string; children: string }) { return <><Text style={styles.section}>{title}</Text><Text style={styles.body}>{children}</Text></>; }
const styles = StyleSheet.create({ back: { minHeight: 44, justifyContent: 'center' }, backText: { color: colors.blue, fontWeight: '800' }, title: { ...type.pageTitle }, section: { ...type.sectionTitle, marginTop: spacing.xl }, body: { ...type.body, color: colors.gray, marginTop: spacing.sm } });
