import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Badge } from '@/components/Badge';
import { BrandHeader } from '@/components/BrandHeader';
import { Button } from '@/components/Button';
import { Card } from '@/components/Card';
import { Screen } from '@/components/Screen';
import { colors, spacing, type } from '@/constants/theme';

const members = [{ alias: 'MiaManager', role: 'Owner' }, { alias: 'BranchLead7', role: 'Branch manager' }, { alias: 'NumbersNeighbor', role: 'Analyst' }];

export default function CompanyDashboard() {
  const router = useRouter();
  return <Screen header={<BrandHeader compact title="Company dashboard" />}><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹ Account</Text></Pressable><Text style={styles.title}>BlueWater Plumbing</Text><View style={styles.badges}><Badge label="Company" tone="green" /><Badge label="Authority verified" tone="blue" /></View><Card><Text style={styles.section}>Inland Empire Branch</Text><Text style={styles.body}>4.6 service rating · 41 unique customers</Text><Text style={styles.note}>Branch/team ratings are primary. A company-wide aggregate, if enabled later, is separately labeled.</Text><View style={styles.areaRow}><View><Text style={styles.big}>3 / 1,000</Text><Text style={styles.note}>service areas</Text></View><Button label="Bulk manage areas" tone="quiet" onPress={() => Alert.alert('Branch coverage', 'Parent-area selection stores hierarchical choices without pre-expanding every descendant locality.')} /></View></Card><Card><Text style={styles.section}>Team access</Text>{members.map((member) => <View key={member.alias} style={styles.member}><View style={styles.flex}><Text style={styles.memberAlias}>{member.alias}</Text><Text style={styles.note}>{member.role}</Text></View><Text style={styles.audit}>Audited</Text></View>)}<Button label="Invite by private email" tone="secondary" onPress={() => Alert.alert('Team invitation', 'Invitations grant owner, admin, branch manager, or analyst permissions. Public pages show aliases only.')} style={styles.button} /></Card><Card><Text style={styles.section}>Local promotion</Text><Badge label="Controlled release gate" tone="orange" /><Text style={styles.body}>Future concept: USD $10 per selected HouseFriends service area for 30 days.</Text><Text style={styles.note}>Activation requires country legal approval, platform billing approval, total-price confirmation, monthly cap, renewal disclosure, receipt, and cancellation. Paid placement never changes ratings or hides reviews.</Text><Button label="Promotion unavailable in this build" disabled style={styles.button} /></Card><Card><Text style={styles.section}>Audit trail</Text><Text style={styles.body}>Branch coverage updated by MiaManager</Text><Text style={styles.note}>All company mutations store actor alias, HF-ID, time, object, and change summary.</Text></Card></Screen>;
}

const styles = StyleSheet.create({ back: { minHeight: 44, justifyContent: 'center' }, backText: { color: colors.blue, fontWeight: '800' }, title: { ...type.pageTitle }, badges: { flexDirection: 'row', gap: 6, marginVertical: spacing.md }, section: type.sectionTitle, body: { ...type.body, marginTop: spacing.sm }, note: { ...type.caption, marginTop: 4 }, areaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: spacing.md }, big: { color: colors.greenDark, fontSize: 28, fontWeight: '900' }, member: { flexDirection: 'row', alignItems: 'center', minHeight: 58, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.grayLight }, flex: { flex: 1 }, memberAlias: { ...type.cardTitle, fontSize: 15 }, audit: { ...type.caption, color: colors.greenDark, fontWeight: '700' }, button: { marginTop: spacing.md } });
