import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { useRouter } from 'expo-router';
import { Badge } from '@/components/Badge';
import { BrandHeader } from '@/components/BrandHeader';
import { Button } from '@/components/Button';
import { Card } from '@/components/Card';
import { Screen } from '@/components/Screen';
import { colors, spacing, type } from '@/constants/theme';

export default function ProviderDashboard() {
  const router = useRouter();
  return <Screen header={<BrandHeader compact title="Service Friend dashboard" />}><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹ Account</Text></Pressable><Text style={styles.title}>Alex Home Repair</Text><View style={styles.badges}><Badge label="Individual" tone="green" /><Badge label="Claimed" tone="blue" /><Badge label="Organic presence" /></View><View style={styles.metrics}><Metric value="4.8" label="service rating" /><Metric value="24" label="unique customers" /><Metric value="8" label="verified referrals" /></View><Card><Text style={styles.section}>Public identity</Text><Text style={styles.body}>Alias: AlexFixes · HF-PR0V1D3R</Text><Text style={styles.note}>Your sign-in name and email are never public. “Alex Home Repair” is your voluntary trade name.</Text></Card><Card><Text style={styles.section}>Service coverage</Text><Text style={styles.big}>2 / 100</Text><Text style={styles.body}>HouseFriends service areas selected</Text><Text style={styles.note}>Choose familiar administrative areas in bulk. Do not select hundreds of public anchor points.</Text><Button label="Manage coverage" tone="quiet" onPress={() => Alert.alert('Coverage editor', 'Hierarchical area selection is ready for the connected country service-area dataset.')} style={styles.button} /></Card><Card><Text style={styles.section}>Categories</Text><Text style={styles.body}>Handyman · Carpenter / Woodwork · Drywall / Plaster</Text><Text style={styles.note}>3 of 5 categories selected</Text></Card><Card><Text style={styles.section}>Recent community experience</Text><Text style={styles.body}>“Repaired a loose stair railing and patched drywall”</Text><Text style={styles.note}>Providers may respond or report, but cannot edit a customer’s genuine experience.</Text><Button label="Write a public response" tone="secondary" onPress={() => Alert.alert('Provider response', 'Response composer opens after the production database is connected.')} style={styles.button} /></Card><Card><Text style={styles.section}>Contact and business card</Text><Text style={styles.body}>Provider-controlled public contact is current.</Text><Text style={styles.note}>Customer-uploaded cards remain private and pending until you approve or claim them.</Text></Card></Screen>;
}

function Metric({ value, label }: { value: string; label: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const styles = StyleSheet.create({ back: { minHeight: 44, justifyContent: 'center' }, backText: { color: colors.blue, fontWeight: '800' }, title: { ...type.pageTitle, marginTop: spacing.sm }, badges: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginVertical: spacing.md }, metrics: { flexDirection: 'row', backgroundColor: colors.navy, borderRadius: 18, paddingVertical: spacing.lg }, metric: { flex: 1, alignItems: 'center', paddingHorizontal: 5 }, metricValue: { color: colors.white, fontWeight: '900', fontSize: 23 }, metricLabel: { color: '#DDE7F4', textAlign: 'center', fontSize: 10 }, section: type.sectionTitle, body: { ...type.body, marginTop: spacing.sm }, note: { ...type.caption, marginTop: spacing.sm }, big: { color: colors.greenDark, fontSize: 30, fontWeight: '900', marginTop: spacing.sm }, button: { marginTop: spacing.md } });
