export const PROVIDER_AREA_CAPS: Readonly<{ individual: 100; company: 1000 }>;
export const MAX_PROVIDER_CATEGORIES: 5;
export const MAX_SAFE_ANCHORS: 5;
export const RATING_KEYS: readonly ['quality', 'value', 'reliability', 'communication', 'recommend'];
export const APPROVED_ANCHOR_CLASSES: readonly string[];
export function validateAlias(alias: string): string;
export function isValidHfId(hfId: string): boolean;
export function createHfId(source: string): string;
export function validateProviderCategories(categoryIds: string[]): string[];
export function validateServiceAreas(kind: 'individual' | 'company', serviceAreaIds: string[]): string[];
export function chooseSafeAnchors<T extends { id: string; class: string; distanceMeters: number }>(anchors: T[]): T[];
export function validateSafeAnchor(anchor: { class: string; name?: string; serviceAreaId?: string }): true;
export function normalizeMoney(amount: number, currency: string): { costMinor: number; currency: string };
export function validateRating(rating: Record<string, number>): true;
export function averageRating(rating: Record<string, number>): number;
export function aggregateUniqueCustomerRatings(rows: { customerId: string; updatedAt: string; rating: Record<string, number> }[]): { average: number; customerCount: number };
export function validateExperienceDraft(draft: { serviceMonth: string; comment: string; serviceItem: string; rating: Record<string, number>; anchor: object; costMinor: number; currency: string }): true;
export function transitionReferral(current: 'none' | 'helpful' | 'verified', requested: 'helpful' | 'verified'): 'helpful' | 'verified';
export function referralBadge(verifiedCount: number): string | null;
export function dedupeDiscoveryResults<T extends { providerId: string; branchId?: string; placement: 'organic' | 'sponsored'; rating?: number }>(results: T[]): T[];
export function mayActivateSponsoredPlacement(gate: { enabled: boolean; legalApproved: boolean; billingApproved: boolean }): boolean;
export function regulatedCategoryState(gate: { enabled: boolean; legalApproved: boolean; verificationAvailable: boolean }): 'unavailable' | 'verification_available' | 'license_unverified';
export function eligibleSearchAreas(resolution: { sourceAreaId: string; adjacentAreaIds?: string[] }): string[];
export function containsLikelyPrivateAddress(input: string): boolean;
export function assertNoPrivateAddress(content: { comment: string; serviceItem: string }): true;
export function validateThankYouReward(reward: { sentimentRequired?: boolean; ratingMinimum?: number; reviewRemovalRequired?: boolean; verifiedReferralRequired?: boolean }): true;
export function normalizeReportReason(reason: string): 'privacy' | 'fraud' | 'abuse' | 'conflict' | 'other';
